AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda Layers

Resources:     
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      MemorySize: 512
      Runtime: dotnetcore3.1
      Architectures:
        - x86_64    
      Handler: HelloWorldApi::HelloWorldApi.Function::FunctionHandler
      CodeUri: ./src/HelloWorldApi/
      Layers : 
        - arn:aws:lambda:us-east-2:025381531841:layer:MyDotNetLambdaLayer31:1
      Events:
        ListPosts:
          Type: Api
          Properties:
            Path: /
            Method: get